create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority bigint not null, primary key (role_id, authority)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FK1709s99yg542kt8uogm30416b foreign key (authority) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority bigint not null, primary key (role_id, authority)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FK1709s99yg542kt8uogm30416b foreign key (authority) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table authorities (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities (id);
alter table role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles (id);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
