create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id), unique(name)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, username varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, username varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, username varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, username varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, username varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, username varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, username varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, username varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null, is_account_non_locked true, password varchar(255) not null, user_name varchar(255) not null, role_id bigint not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles (id);
